# Generated by Django 5.1.3 on 2025-01-08 13:34

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'], "Можно загружать только следующие файлы 'jpg', 'jpeg', 'png'")], verbose_name='Аватар'),
        ),
    ]
