# Generated by Django 5.1.3 on 2024-11-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('moderated', 'Модерированная'), ('published', 'Опубликована')], default='new', max_length=15, verbose_name='Статус'),
        ),
    ]
