# Generated by Django 5.1.3 on 2024-12-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_article_status'),
        ('webapp', '0002_genre_article_genre'),
    ]

    operations = [
    ]
