# Generated by Django 5.1.3 on 2024-12-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_merge_0002_article_status_0002_genre_article_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
    ]
