# Generated by Django 5.1.3 on 2024-12-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_tag_articletag_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tags_old',
        ),
    ]
