# Generated by Django 5.1.3 on 2024-12-11 13:29

from django.db import migrations

def delete_duplicates_tags(apps, schema_editor):
    Tag = apps.get_model('webapp.Tag')
    duplicates_tags = []
    for tag in Tag.objects.all():
        if tag not in duplicates_tags:
            duplicates = Tag.objects.filter(name=tag.name).exclude(id=tag.id)
            for duplicate in duplicates:
                duplicates_tags.append(duplicate)
                for article in  duplicate.articles.all():
                    article.tags.remove(duplicate)
                    article.tags.add(tag)
    for duplicate in duplicates_tags:
        duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_article_tags_old_delete_articletag'),
    ]

    operations = [
        migrations.RunPython(delete_duplicates_tags, migrations.RunPython.noop),
    ]
