# Generated by Django 5.1.3 on 2024-12-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
