# Generated by Django 5.1.3 on 2024-12-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_article_author_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('change_article_tags', 'Менять теги статье')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
